### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by IanDelMar**
First steps towards what Viktor calls a "proper project".

https://github.com/php-stubs/wordpress-stubs/pull/119#issuecomment-1780197945

Done:
- Move all classes from inside visitor.php to separate files located in the "src/" directory.
- Add tests to ensure that `FunctionMap()` additions are working correctly.

Todo:
* Refactor Visitor.php
* Move `void` and `never` detection outside of the visitor. For detecting void/never we parse the source. This needs to happen on source change only.
* Investigate the potential advantage of utilising doc blocks for  `@phpstan-...`.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Should I merge it and release 6.4?

**Comment by IanDelMar** [comment]
I'd release 6.4 first.

**Comment by szepeviktor** [comment]
Thank you, Safe Ian!

**Comment by szepeviktor** [comment]
The 6.4 branch cannot be merged to master.
Please close this one and open a new PR to master.

Thank you for your contributions.

**Pull request closed without merging**
