### PR TITLE
Improve return type for `get_post_types`

### PR DESCRIPTION
**Pull request by lipemat**
The result of `get_post_type` is an associative array keyed with the post type slugs.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you.
Please show me how it works.
https://developer.wordpress.org/reference/functions/get_post_types/

Even when output=names ?

**Comment by lipemat** [comment]
Yes, all cases including output names have an associative array. 

Here it is using `wp shell`. 

Filtered by `public => true` to keep things reasonably brief. 

```shell
> get_post_types(['public' => true] );
= [
    "post" => "post",
    "page" => "page",
    "attachment" => "attachment",
  ]


> get_post_types(['public' => true], 'names' );
= [
    "post" => "post",
    "page" => "page",
    "attachment" => "attachment",
  ]


> get_post_types(['public' => true], 'objects' );
= [                                                       
    "post" => WP_Post_Type {#2234                         
      +name: "post",                                      
      +label: "Posts",                                    
      +labels: {#2239                                     
        +"name": "Posts",                                 
        +"singular_name": "Post",                         
        +"add_new": "Add New Post",                       
        +"add_new_item": "Add New Post",                  
        +"edit_item": "Edit Post",                        
        +"new_item": "New Post",                          
        +"view_item": "View Post",                        
        +"view_items": "View Posts",                      
        +"search_items": "Search Posts",                  
        +"not_found": "No posts found.",                  
        +"not_found_in_trash": "No posts found in Trash.",
        +"parent_item_colon": null,                       
        +"all_items": "All Posts",                        
        +"archives": "Post Archives",
        +"attributes": "Post Attributes",
        +"insert_into_item": "Insert into post",
        +"uploaded_to_this_item": "Uploaded to this post",
        +"featured_image": "Featured image",
        +"set_featured_image": "Set featured image",
        +"remove_featured_image": "Remove featured image",
        +"use_featured_image": "Use as featured image",
        +"filter_items_list": "Filter posts list",
        +"filter_by_date": "Filter by date",
        +"items_list_navigation": "Posts list navigation",
        +"items_list": "Posts list",
        +"item_published": "Post published.",
        +"item_published_privately": "Post published privately.",
        +"item_reverted_to_draft": "Post reverted to draft.",
        +"item_trashed": "Post trashed.",
        +"item_scheduled": "Post scheduled.",
        +"item_updated": "Post updated.",
        +"item_link": "Post Link",
        +"item_link_description": "A link to a post.",
        +"menu_name": "Posts",
        +"name_admin_bar": "Post",
      },
      +description: "",
      +public: true,
      +hierarchical: false,
      +exclude_from_search: false,
      +publicly_queryable: true,
      +show_ui: true,
      +show_in_menu: true,
      +show_in_nav_menus: true,
      +show_in_admin_bar: true,
      +menu_position: 5,
      +menu_icon: "dashicons-admin-post",
      +capability_type: "post",
      +map_meta_cap: true,
      +register_meta_box_cb: null,
      +taxonomies: [],
      +has_archive: false,
      +query_var: false,
      +can_export: true,
      +delete_with_user: true,
      +template: [],
      +template_lock: false,
      +_builtin: true,
      +_edit_link: "post.php?post=%d",
      +cap: {#2236
        +"edit_post": "edit_post",
        +"read_post": "read_post",
        +"delete_post": "delete_post",
        +"edit_posts": "edit_posts",
        +"edit_others_posts": "edit_others_posts",
        +"delete_posts": "delete_posts",
        +"publish_posts": "publish_posts",
        +"read_private_posts": "read_private_posts",
        +"read": "read",
        +"delete_private_posts": "delete_private_posts",
        +"delete_published_posts": "delete_published_posts",
        +"delete_others_posts": "delete_others_posts",
        +"edit_private_posts": "edit_private_posts",
        +"edit_published_posts": "edit_published_posts",
        +"create_posts": "edit_posts",
      },
      +rewrite: false,
      +show_in_rest: true,
      +rest_base: "posts",
      +rest_namespace: "wp/v2",
      +rest_controller_class: "WP_REST_Posts_Controller",
      +rest_controller: WP_REST_Posts_Controller {#3178},
      +revisions_rest_controller_class: false,
      +revisions_rest_controller: WP_REST_Revisions_Controller {#3180},
      +autosave_rest_controller_class: false,
      +autosave_rest_controller: WP_REST_Autosaves_Controller {#3182},
      +late_route_registration: false,
    },
    "page" => WP_Post_Type {#1800
      +name: "page",
      +label: "Pages",
      +labels: {#2237
        +"name": "Pages",
        +"singular_name": "Page",
        +"add_new": "Add New Page",
        +"add_new_item": "Add New Page",
        +"edit_item": "Edit Page",
        +"new_item": "New Page",
        +"view_item": "View Page",
        +"view_items": "View Pages",
        +"search_items": "Search Pages",
        +"not_found": "No pages found.",
        +"not_found_in_trash": "No pages found in Trash.",
        +"parent_item_colon": "Parent Page:",
        +"all_items": "All Pages",
        +"archives": "Page Archives",
        +"attributes": "Page Attributes",
        +"insert_into_item": "Insert into page",
        +"uploaded_to_this_item": "Uploaded to this page",
        +"featured_image": "Featured image",
        +"set_featured_image": "Set featured image",
        +"remove_featured_image": "Remove featured image",
        +"use_featured_image": "Use as featured image",
        +"filter_items_list": "Filter pages list",
        +"filter_by_date": "Filter by date",
        +"items_list_navigation": "Pages list navigation",
        +"items_list": "Pages list",
        +"item_published": "Page published.",
        +"item_published_privately": "Page published privately.",
        +"item_reverted_to_draft": "Page reverted to draft.",
        +"item_trashed": "Page trashed.",
        +"item_scheduled": "Page scheduled.",
        +"item_updated": "Page updated.",
        +"item_link": "Page Link",
        +"item_link_description": "A link to a page.",
        +"menu_name": "Pages",
        +"name_admin_bar": "Page",
      },
      +description: "",
      +public: true,
      +hierarchical: true,
      +exclude_from_search: false,
      +publicly_queryable: false,
      +show_ui: true,
      +show_in_menu: true,
      +show_in_nav_menus: true,
      +show_in_admin_bar: true,
      +menu_position: 20,
      +menu_icon: "dashicons-admin-page",
      +capability_type: "page",
      +map_meta_cap: true,
      +register_meta_box_cb: null,
      +taxonomies: [],
      +has_archive: false,
      +query_var: false,
      +can_export: true,
      +delete_with_user: true,
      +template: [],
      +template_lock: false,
      +_builtin: true,
      +_edit_link: "post.php?post=%d",
      +cap: {#1805
        +"edit_post": "edit_page",
        +"read_post": "read_page",
        +"delete_post": "delete_page",
        +"edit_posts": "edit_pages",
        +"edit_others_posts": "edit_others_pages",
        +"delete_posts": "delete_pages",
        +"publish_posts": "publish_pages",
        +"read_private_posts": "read_private_pages",
        +"read": "read",
        +"delete_private_posts": "delete_private_pages",
        +"delete_published_posts": "delete_published_pages",
        +"delete_others_posts": "delete_others_pages",
        +"edit_private_posts": "edit_private_pages",
        +"edit_published_posts": "edit_published_pages",
        +"create_posts": "edit_pages",
      },
      +rewrite: false,
      +show_in_rest: true,
      +rest_base: "pages",
      +rest_namespace: "wp/v2",
      +rest_controller_class: "WP_REST_Posts_Controller",
      +rest_controller: WP_REST_Posts_Controller {#3183},
      +revisions_rest_controller_class: false,
      +revisions_rest_controller: WP_REST_Revisions_Controller {#3185},
      +autosave_rest_controller_class: false,
      +autosave_rest_controller: WP_REST_Autosaves_Controller {#3187},
      +late_route_registration: false,
    },
    "attachment" => WP_Post_Type {#1804
      +name: "attachment",
      +label: "Media",
      +labels: {#2235
        +"name": "Media",
        +"singular_name": "Media",
        +"add_new": "Add New Media File",
        +"add_new_item": "Add New Post",
        +"edit_item": "Edit Media",
        +"new_item": "New Post",
        +"view_item": "View Attachment Page",
        +"view_items": "View Posts",
        +"search_items": "Search Posts",
        +"not_found": "No posts found.",
        +"not_found_in_trash": "No posts found in Trash.",
        +"parent_item_colon": null,
        +"all_items": "Media",
        +"archives": "Media",
        +"attributes": "Attachment Attributes",
        +"insert_into_item": "Insert into post",
        +"uploaded_to_this_item": "Uploaded to this post",
        +"featured_image": "Featured image",
        +"set_featured_image": "Set featured image",
        +"remove_featured_image": "Remove featured image",
        +"use_featured_image": "Use as featured image",
        +"filter_items_list": "Filter posts list",
        +"filter_by_date": "Filter by date",
        +"items_list_navigation": "Posts list navigation",
        +"items_list": "Posts list",
        +"item_published": "Post published.",
        +"item_published_privately": "Post published privately.",
        +"item_reverted_to_draft": "Post reverted to draft.",
        +"item_trashed": "Post trashed.",
        +"item_scheduled": "Post scheduled.",
        +"item_updated": "Post updated.",
        +"item_link": "Post Link",
        +"item_link_description": "A link to a post.",
        +"menu_name": "Media",
        +"name_admin_bar": "Media",
      },
      +description: "",
      +public: true,
      +hierarchical: false,
      +exclude_from_search: false,
      +publicly_queryable: true,
      +show_ui: true,
      +show_in_menu: true,
      +show_in_nav_menus: false,
      +show_in_admin_bar: true,
      +menu_position: null,
      +menu_icon: "dashicons-admin-media",
      +capability_type: "post",
      +map_meta_cap: true,
      +register_meta_box_cb: null,
      +taxonomies: [],
      +has_archive: false,
      +query_var: false,
      +can_export: true,
      +delete_with_user: true,
      +template: [],
      +template_lock: false,
      +_builtin: true,
      +_edit_link: "post.php?post=%d",
      +cap: {#1809
        +"edit_post": "edit_post",
        +"read_post": "read_post",
        +"delete_post": "delete_post",
        +"edit_posts": "edit_posts",
        +"edit_others_posts": "edit_others_posts",
        +"delete_posts": "delete_posts",
        +"publish_posts": "publish_posts",
        +"read_private_posts": "read_private_posts",
        +"read": "read",
        +"delete_private_posts": "delete_private_posts",
        +"delete_published_posts": "delete_published_posts",
        +"delete_others_posts": "delete_others_posts",
        +"edit_private_posts": "edit_private_posts",
        +"edit_published_posts": "edit_published_posts",
        +"create_posts": "upload_files",
      },
      +rewrite: false,
      +show_in_rest: true,
      +rest_base: "media",
      +rest_namespace: "wp/v2",
      +rest_controller_class: "WP_REST_Attachments_Controller",
      +rest_controller: WP_REST_Attachments_Controller {#3188},
      +revisions_rest_controller_class: false,
      +revisions_rest_controller: null,
      +autosave_rest_controller_class: false,
      +autosave_rest_controller: null,
      +late_route_registration: false,
    },
  ]
```

**Comment by szepeviktor** [comment]
@IanDelMar @johnbillion Could you help me please?

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
