### PR TITLE
Add conditional return types for `array|WP_Taxonomy`

### PR DESCRIPTION
**Pull request by IanDelMar**
Adds conditional return type for
* `get_attachment_taxonomies()`
* `get_taxonomies_for_attachments()`
* `get_post_stati()`

Adds additional tests for `get_object_taxonomies()`.

### CODE REVIEW

**Comment by szepeviktor** [comment]
What a great experience to handle a PR that has ✔️ ✔️ 
😊

**Comment by szepeviktor** [comment]
These tests are so thorough.
Thank you!

**Comment by IanDelMar** [comment]
But they're failing for `get_post_stati()` if output is something different than `'names'`. It seems that this has something to do with `stdClass`.

**Comment by IanDelMar** [comment]
Ok, found the problem.

**Pull request merged**
