### PR TITLE
Remove travis leftovers

### PR DESCRIPTION
**Pull request by IanDelMar**
As far as I can tell, we're not using travis anymore.

### CODE REVIEW

**Comment by szepeviktor** [comment]
I use Travis but the php-stub org has not received OSS credits.

**Comment by szepeviktor** [comment]
> We are unable to start your build at this time. You exceeded the number of users allowed for your plan. Please review your plan details and follow the steps to resolution.

**Comment by szepeviktor** [comment]
TravisCI was fun.
GHA is not fun.

**Comment by IanDelMar** [comment]
:-(

**Pull request merged**
