### PR TITLE
Remove code duplication for 6.2 handling

### PR DESCRIPTION
**Pull request by johnbillion**
See #71.

* [X] generate.sh
* [X] visitor62.php
* [ ] functionMap62.php

### CODE REVIEW

**Comment by IanDelMar** [comment]
functionMap.php and functionMap62.php only differ in `$httpReturnType` and visitor.php and visitor62.php only differ in using functionMap.php or functionMap62.php, right?

Wouldn't it then be possible to define `$httpReturnType` in functionMap.php like this:
```php
$httpReturnType = 'array{headers: \WpOrg\Requests\Utility\CaseInsensitiveDictionary, body: string, response: array{code: int,message: string}, cookies: array<int, \WP_HTTP_Cookie>, filename: string|null, http_response: \WP_HTTP_Requests_Response}|\WP_Error';
if (file_exists(__DIR__.'/source/wordpress/wp-includes/Requests/Cookie/Jar.php')) {
    $httpReturnType = 'array{headers: \Requests_Utility_CaseInsensitiveDictionary, body: string, response: array{code: int,message: string}, cookies: array<int, \WP_HTTP_Cookie>, filename: string|null, http_response: \WP_HTTP_Requests_Response}|\WP_Error';
}
```

and only have one visitor and one functionsMap file?

**Comment by szepeviktor** [comment]
> Wouldn't it then be possible to define `$httpReturnType` in functionMap.php like this:

Yes!!

**Comment by johnbillion** [comment]
I did wonder that but I thought we might like to keep the version sniffing code in generate.sh. What do you think Viktor?

**Comment by szepeviktor** [comment]
I'd like to keep `functionMap62.php` 🙃 

Please go with Ian's solution.

**Comment by szepeviktor** [comment]
Yes.

**Pull request closed without merging**
