### PR TITLE
Update stubs for WordPress 5.8.3

### PR DESCRIPTION
**Pull request by swissspidy**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Have you ran the release script checking all 4.7 4.8 4.9 5.0 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 versions?

**Comment by szepeviktor** [comment]
Excuse me for being late with the releases!
https://github.com/php-stubs/wordpress-stubs/commits/master 🍏

**Comment by szepeviktor** [comment]
BTW `source/composer.json` also needs to be updated 💡

**Comment by swissspidy** [comment]
Ah, thanks! Somehow forgot to commit that change.

Thanks for the manual update.

**Pull request closed without merging**
