### PR TITLE
Add ReturnTypeWillChange for PHP 8.1

### PR DESCRIPTION
**Pull request by szepeviktor**
@Mte90 👀 

From  #41

### CODE REVIEW

**Comment by szepeviktor** [comment]
@johnbillion Please start me up with 1 sentence how to insert `#[\ReturnTypeWillChange]` before method listed in this PR.
Thank you.

**Comment by Mte90** [comment]
I executed phpstan with those tags and I saw no errors as there also other uses of that attribute in the stubs https://github.com/WordPress/wordpress-develop/search?q=ReturnTypeWillChange

**Comment by szepeviktor** [comment]
> I saw no errors as there also other uses of that attribute

Please consider opening a core trac ticket! 🚀

**Comment by szepeviktor** [comment]
> there are various tickets for php 8 in wordpress

1.    WordPress core is not fully PHP 8.1 compatible
2.    The current WordPress ecosystem is not PHP 8.0 compatible
3.    WordPress installations live happily on PHP 7.4 as of 2022

Currently WP v6 contains `WordPress/Request` v1!
`WordPress/Request` v2 has these problems fixed.

I couldn't find the issue but I had the idea **to exclude** packages included in WP core.

- ID3
- PHPMailer
- WordPress/Request
- SimplePie

Would like to be involved?

**Comment by Mte90** [comment]
I don't see errors from those packages... maybe they are written the right way

**Comment by szepeviktor** [comment]
This is a dead end.
https://github.com/php-stubs/wordpress-stubs/commit/769dd33a097dbe6c0ac1101bf51195ca9bac6121

**Comment by Mte90** [comment]
Well the important part is that at least there will be less issues with this project :-D

**Pull request closed without merging**
