### PR TITLE
Conditionally add return type for WP_Http::request

### PR DESCRIPTION
**Pull request by IanDelMar**
Removes duplicate return tag for `WP_Http::request()`

### CODE REVIEW

**Comment by szepeviktor** [comment]
Hello guys!
This has turned into a wrong direction.

How to handle ever-growing number of PHPStan tags in core???

**Comment by szepeviktor** [comment]
How about not adding a tag that already exists?
Could we do that?
(and write a log line)

**Comment by IanDelMar** [comment]
We can. But then it is lost for each previous version as well.

**Comment by szepeviktor** [comment]
> But then it is lost for each previous version as well.

Why? I do not understand.

Only not add our tag when one already exists in the current version.

**Comment by IanDelMar** [comment]
Ah, you mean not adding it in the visitor? We can avoid it that way, but at the cost of losing the ability to override incorrect tags that were added automatically.

**Comment by szepeviktor** [comment]
> to override incorrect tags that were added automatically.

That is better!

So if there is already a `@phpstan-*` tag in core we overwrite that: core's tag will be removed, not ours.

**Comment by szepeviktor** [comment]
> core's tag will be removed, not ours.

The opposite of this PR.

**Comment by IanDelMar** [comment]
Not sure what you mean by 
> So if there is already a `@phpstan-*` tag in core we overwrite that: core's tag will be removed, not ours.

There is no `@phpstan-*` tag in core. They are all generated by the visitor.

**Comment by szepeviktor** [comment]
I see!!

"Autogenerated" means we read `@return { @type ... }` and autogenerate a phpstan tag.

Okay. Then drop the one from `functionMap.php`.

**Comment by szepeviktor** [comment]
but no `$wp_version` please

**Comment by IanDelMar** [comment]
> Okay. Then drop the one from `functionMap.php`.

That's what I did. We can implement the same behavior via the visitor, but I won't have time for this this week.

**Comment by IanDelMar** [comment]
#265

**Pull request closed without merging**
