### PR TITLE
Disallow the use of query strings

### PR DESCRIPTION
**Pull request by IanDelMar**
This PR adds array shapes for the `$args` parameter to the functionsMap.php for
* `get_objects_in_term()`
* `WP_List_Table::set_pagination_args()`
* `WP_Post_Type::__construct()`
* `WP_Taxonomy::__construct()`
* `wp_widget_rss_form()`.

As already done with other functions in the WP stubs this disallows the use of query string for the functions listed above.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you Ian!
Could you update the stubs file?

**Comment by herndlm** [comment]
Does that mean that all those types are not in the stubs already I suppose? Just asking because I remember registering a post type recently and it did enforce the arg type with keys properly

**Comment by herndlm** [comment]
> Does that mean that all those types are not in the stubs already I suppose? Just asking because I remember registering a post type recently and it did enforce the arg type with keys properly

just checked, looks like I was using `register_post_type()` and not the constructor 👍

**Comment by IanDelMar** [comment]
This needs to go into functionMap62.php as well, right?

**Comment by szepeviktor** [comment]
> This needs to go into functionMap62.php as well, right?

Yes.
John promised he will thing about abolishing "62" files.

**Comment by szepeviktor** [comment]
@IanDelMar I'm very glad that you continue with this PR.

**Comment by IanDelMar** [comment]
The PR should be up to date now

**Comment by szepeviktor** [comment]
Thank you!

**Comment by johnbillion** [comment]
@IanDelMar What's your use case for needing the shape of the args for `WP_Post_Type::__construct()` and `WP_Taxonomy::__construct()`? We've already got them for `register_post_type()` and `register_taxonomy()`.

Having those shapes defined in this repo increases the maintenance burden and the chance that they get out of sync with the args in core.

The `visitor.php` class supports inherited args from other functions when the `@see` tag is used in the parameter description (see #49) so we can do this via WordPress core and then remove the `$registerPostTypeArgsType` and `$registerTaxonomyArgsType` definitions in this repo.

**Comment by IanDelMar** [comment]
@johnbillion Maybe they are not needed. In fact this is not about the shapes at all but removing the string from `$args`
```php
	/**
	 * Constructor.
	 *
	 * See the register_post_type() function for accepted arguments for `$args`.
	 *
	 * Will populate object properties from the provided arguments and assign other
	 * default properties based on that information.
	 *
	 * @since 4.6.0
	 *
	 * @see register_post_type()
	 *
	 * @param string       $post_type Post type key.
	 * @param array|string $args      Optional. Array or string of arguments for registering a post type.
	 *                                Default empty array.
	 */
	public function __construct( $post_type, $args = array() ) {
		$this->name = $post_type;


		$this->set_props( $args );
	}
```
Source: https://github.com/WordPress/wordpress-develop/blob/6.2/src/wp-includes/class-wp-post-type.php#L399-L419

If there's a better way to do this, I'm happy to learn!

**Comment by johnbillion** [comment]
Got it. I'll take a look.

**Pull request merged**
