### PR TITLE
Add WP_Theme magic properties

### PR DESCRIPTION
**Pull request by IanDelMar**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you.

Does anyone use this package?

**Comment by IanDelMar** [comment]
Which package are you referring to?

**Comment by szepeviktor** [comment]
This one.

Because I'd like to be involved in WordPress development!

**Comment by IanDelMar** [comment]
I guess

image

image

**Comment by szepeviktor** [comment]
That was not me.

I do not have clients with WordPress development. That is why I am depressed when it comes to this package. _Give me work!!_

**Comment by IanDelMar** [comment]
I completely understand your frustration and sincerely hope that things turn around for you soon.

**Pull request merged**
