### PR TITLE
Add stubs for WP 6.5

### PR DESCRIPTION
**Pull request by IanDelMar**
This pull request updates the stubs to WordPress 6.5.

Changes to functionMap.php:

- Removal of `WP_List_Table::display_tablenav` and `WP_List_Table::pagination`. The visitor now adds these PHPStan tags without relying on `functionMap.php`.
- Removal of optional indicators (`?`) for the return type of `WP_Filesystem_*::dirlist()` in accordance with the description in the [documentation](https://developer.wordpress.org/reference/classes/wp_filesystem_base/dirlist/).

Notes:
- `WP_Filesystem_*::dirlist()`: There are now two `@phpstan-return`, one added by the visitor using `@type` and one previously added via `functionMap.php`. There are two issues: the details provided by the new tag are slightly reduced (see `type` key), which should not be problematic from my perspective. Additionally, the array key is now specified as int|string, which I believe is incorrect; it should be string. Depending on how PHPStan handles duplicate entries, which I'm unsure of but assume to be based on the last entry, I would recommend retaining the PHPStan information from `functionMap.php`.
- `WP_Font_Face::generate_and_print()`: The visitor no longer includes additions stemming from `@type`. I think this is because we cannot handle `array[][]`. Is `array[][]` a valid syntax?
- `wp_get_avif_info()`: The visitor no longer includes additions stemming from `@type`, possibly due to incorrect indentation. This should be addressed in the core.
- `wp_enqueue_script_module()`: See to `wp_get_avif_info()`.

Concerning the idea of ceasing to add additional tags if a tag with the same name is already present (#163):
- This implies that overriding tags added by the visitor before functionMap tags are applied is no longer possible. Consequently, we wouldn't be able to correct or refine these additions.
- Conversely, if functionMap tags are added first, we may overlook whether the functionMap entry is still necessary or correct.
- I suggest continuing to add all tags and did not implement any change to the current behavior of adding all additions.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you Ian!
Could you please regenerate stubs for the latest tag without adding 6.5?

**Comment by szepeviktor** [comment]
You know what?!

**Comment by IanDelMar** [comment]
> Thank you Ian! Could you please regenerate stubs for the latest tag without adding 6.5?

Sorry, didn't see this before. Anything you still want me to do?

**Comment by szepeviktor** [comment]
No. Everything is released.

**Comment by swissspidy** [comment]
@IanDelMar Thanks for working on this! Would you mind creating core trac tickets for those two functions?

**Comment by swissspidy** [comment]
> * `wp_get_avif_info()`: The visitor no longer includes additions stemming from `@type`, possibly due to incorrect indentation. This should be addressed in the core.
> * `wp_enqueue_script_module()`: See to `wp_get_avif_info()`.

So I just looked into those. Unfortunately, this non-standard phpdoc format for arrays is part of the WordPress coding standards. It's not limited to these two function; just search the code base for `@return array {` and you'll find lots of examples. We'll have to work around this or make a proposal for core to change its standards or add `@phpstan-*` tags in addition to those 🤷 😞

**Comment by szepeviktor** [comment]
> add `@phpstan-*` tags

Yes. Please have core add ALL of our tags in functionMap.

**Comment by IanDelMar** [comment]
> We'll have to work around this

The visitor is aware of this notation for arrays! However, according to the WordPress coding standards, it should be indented by 4 spaces or a multiple thereof. This is what the visitor is seeking but can't find for these two functions. Therefore, it should be fixed in WP core.

**Comment by swissspidy** [comment]
Oh, ok! Let me take another look next week then

**Comment by IanDelMar** [comment]
> Alright, https://core.trac.wordpress.org/changeset/58037 should fix this

These haven't made it into core yet, right?

**Comment by swissspidy** [comment]
That‘s in core :) just not in a published release. That will be WP 6.6, due out this summer

**Pull request merged**
