### PR TITLE
Release 6.4

### LINKED ISSUE #114: 6.4 new see tag
```diff
-         * @param array   $args              An array of arguments. @see wp_terms_checklist()
+         * @param array   $args              An array of arguments. See {@see wp_terms_checklist()}.
```

It makes phpstan-param tag disappear.
@johnbillion Please help me. You are WordPress for me.

https://github.com/php-stubs/wordpress-stubs/commit/1ad360f8519773e0cce1658d5f443212ee4dc6ad 👀

### PR DESCRIPTION
**Pull request by szepeviktor**
Waiting for 7th of November.

Closes #114

### CODE REVIEW

**Comment by IanDelMar** [comment]
https://wordpress.org/news/2023/11/shirley/

**Comment by szepeviktor** [comment]
@johnbillion @IanDelMar I am unable to manage these commits.

Releasing 6.4 from master only.

Does this 6.4 branch has something that needs to be in this release?

**Comment by szepeviktor** [comment]
> Does this 6.4 branch has something that needs to be in this release?

Sorry, I do not care about it.

**Comment by IanDelMar** [comment]
I can check in the next few days whether anything is missing.

**Pull request closed without merging**
