### PR TITLE
Apply coding standards

### PR DESCRIPTION
**Pull request by IanDelMar**
Uses [szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset](https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset)

A first round of fixes. I will do some more, but feel free to merge any time Viktor.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Noooooooooooooooooooooo! This is not a proper project.
Proper projects have all their byte checked in each commit.
https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows

I let you send any kind of PR.

**Comment by szepeviktor** [comment]
Proper projects should have an `src/` directory and a lot of other stuff.
https://github.com/szepeviktor/github-repository-inspection

**Comment by szepeviktor** [comment]
We could make this package very nice.
The first step could be to remove all traces of WordPress 🙃

**Comment by IanDelMar** [comment]
> should have an `visitor/` directory 

Strongly agree!

**Comment by szepeviktor** [comment]
> Strongly agree!

With each class in its own files and a tiny (`return new X();`) `visitor.php`

**Comment by IanDelMar** [comment]
Would love that. I set up a branch like this to fiddle around with the voids and nevers.

**Pull request merged**
