### PR TITLE
Ensure the arguments for cron events are numerically indexed

### PR DESCRIPTION
**Pull request by johnbillion**
The `$args` parameter for functions related to cron events should be a numerically indexed array. Using an associative array means you might be attempting to use the arguments incorrectly in your cron event callback.

### CODE REVIEW

**Comment by szepeviktor** [comment]
> should be a numerically indexed array.

Thank you for this PR.

`array<int ...` does not guaranty that indices are 0, 1, 2 ...
but `list< ...` does.

Could we use `list<>` instead?

**Comment by johnbillion** [comment]
Ah thanks I wasn't sure if that had been implemented in PHPStan yet. I'll take a look.

**Comment by johnbillion** [comment]
It seems that `list` doesn't enforce consecutive indices either. Sad face.

https://phpstan.org/r/a82f653f-449a-4b14-afd0-6e5c0e3900f1

**Comment by szepeviktor** [comment]
It is waiting to be implemented.
https://github.com/phpstan/phpstan/issues/6358

Let's use it anyways!

**Comment by herndlm** [comment]
you both are right :) currently `list<string>` is the same as `array<int, string>`, but this is going to change at some point. the list is definitely the stricter one and could be used too I guess.

**Comment by johnbillion** [comment]
Done!

**Comment by szepeviktor** [comment]
Very neat!

**Comment by herndlm** [comment]
btw sorry for hijacking this, but since it's similar - I recently stumbled over https://github.com/szepeviktor/phpstan-wordpress/issues/85 again. Do you know if this is going to be fixed in WP core @johnbillion or should I open a PR for it here maybe @szepeviktor?

**Comment by szepeviktor** [comment]
Our _chat room_ is open!

But I'm not able to ~~participate~~ precipitate 🌧️ as it is too hot in Budapest.

**Comment by johnbillion** [comment]
@herndlm The core tickets for fixes identified by PHPStan got held up by discussions, I think I need to split them up into smaller issues to get them fixed individually.

**Pull request merged**
