### PR TITLE
Fix issues with _get_list_table()

### LINKED ISSUE #257: _get_list_table issues
The `_get_list_tables()` function has some issues. See #256.

Also, see https://phpstan.org/r/1a049be1-3251-46b0-9e5a-2688de476073. Note the error on line 59, which occurs because `WP_List_Table` itself will never be returned.

This can be partially resolved by updating the functionMap entry as follows:
```php
[
    '_get_list_table' => ['($class_name is T ? new<T> : false)', '@phpstan-template T of' => "'WP_Posts_List_Table'|'WP_Media_List_Table'|'WP_Terms_List_Table'|'WP_Users_List_Table'|'WP_Comments_List_Table'|'WP_Post_Comments_List_Table'|'WP_Links_List_Table'|'WP_Plugin_Install_List_Table'|'WP_Themes_List_Table'|'WP_Theme_Install_List_Table'|'WP_Plugins_List_Table'|'WP_Application_Passwords_List_Table'|'WP_MS_Sites_List_Table'|'WP_MS_Users_List_Table'|'WP_MS_Themes_List_Table'|'WP_Privacy_Data_Export_Requests_List_Table'|'WP_Privacy_Data_Removal_Requests_List_Table'", 'class_name' => 'class-string', 'args' => 'array{screen?: string}'],
]
```
This results in the following stub:
```php
    /**
     * Fetches an instance of a WP_List_Table class.
     *
     * @since 3.1.0
     *
     * @global string $hook_suffix
     *
     * @param string $class_name The type of the list table, which is the class name.
     * @param array  $args       Optional. Arguments to pass to the class. Accepts 'screen'.
     * @return WP_List_Table|false List table object on success, false if the class does not exist.
     * @phpstan-template T of 'WP_Posts_List_Table'|'WP_Media_List_Table'|'WP_Terms_List_Table'|'WP_Users_List_Table'|'WP_Comments_List_Table'|'WP_Post_Comments_List_Table'|'WP_Links_List_Table'|'WP_Plugin_Install_List_Table'|'WP_Themes_List_Table'|'WP_Theme_Install_List_Table'|'WP_Plugins_List_Table'|'WP_Application_Passwords_List_Table'|'WP_MS_Sites_List_Table'|'WP_MS_Users_List_Table'|'WP_MS_Themes_List_Table'|'WP_Privacy_Data_Export_Requests_List_Table'|'WP_Privacy_Data_Removal_Requests_List_Table'
     * @phpstan-param class-string $class_name
     * @phpstan-param array{screen?: string} $args
     * @phpstan-return ($class_name is T ? new<T> : false)
     */
    function _get_list_table($class_name, $args = array())
    {
    }
```
`new<T>` may be used from PHPStan 1.11 onwards.

But this assertion still fails:
```php
/** @var 'WP_Posts_List_Table'|'WP_Post' $className */
assertType('WP_Posts_List_Table|false', _get_list_table($className));
```

Additionally adding `@phpstan-param class-string<WP_List_Table> $class_name` would eliminate all incorrect return types (PHPStan now raises errors if a type is passed that results in an incorrect return type). This might be too restrictive. However, I would interpret the [documentation on `$class_name`](https://developer.wordpress.org/reference/functions/_get_list_table/#parameters) (which states "The type of the _list table_, which is the class name.") to imply that `_get_list_table()` actually requires a `WP_List_Table` class string.

Here is a solution that works without further restricting `$class_name`, though it requires PHPStan 2.0: https://phpstan.org/r/a36a822d-bf1f-4ce7-bd79-c83c817fb032.

Last resort for now: remove `_get_list_table()` and use the return type extension exclusively.

@johnbillion Do you have any idea? What do you think about `@phpstan-param class-string<WP_List_Table> $class_name`? Would this be too restrictive?

### PR DESCRIPTION
**Pull request by IanDelMar**
This PR fixes the return types of `_get_list_table()` and resolves the "not always the same as T. It breaks the contract for some argument types, typically subtypes" issue (see at  [phpstan.org/try](https://phpstan.org/r/da0f2fe2-1125-4b23-aeab-032bef726e34)). The PHPStan version is updated to 1.11 to support `new<T>`.

Compared to the current implementation, we lose the check for whether `$class_name` is a `class-string`. Once we drop support for PHPStan 1.x, we can update `'@phpstan-template T' => 'of string'` to `'@phpstan-template T' => 'of class-string'` to restore the check that `$class_name` is a `class-string`. I don't think that `new<T>` is supported by Psalm.

Once merged, #256 can be closed.

Fixes #257  
Related to #256

Another option to resolve this is to revert migrating the dynamic return type extension from [szepeviktor/phpstan-wordpress](https://github.com/szepeviktor/phpstan-wordpress).

cc: @johnbillion

### CODE REVIEW

**Comment by szepeviktor** [comment]
This is a great PR.

Waiting for John ... and @swissspidy

**Review by szepeviktor — APPROVED** [review]

**Comment by IanDelMar** [comment]
Perhaps @kkmuffme would also like to have a look regarding the Psalm support. Any feedback would be greatly appreciated.

**Comment by johnbillion** [comment]
I don't have time to look deeply into this at the moment. I trust Ian's judgement.

**Comment by szepeviktor** [comment]
Anyone able to answer?

**Comment by IanDelMar** [comment]
> So basically this PR is only needed bc phpstan 1 does not support class-string in template and would be reverted later? Not sure if that change is a good idea to begin with then.

This PR was necessary because we were encountering incorrect return types. Unfortunately, I was unable to resolve the issues with `_get_list_table()` by any other means. Admittedly, I am not an expert in this area, and the only alternative I could think of was to remove it entirely and revert to providing the return types via the return type extension in [szepeviktor/phpstan-wordpress](https://github.com/szepeviktor/phpstan-wordpress). I am, however, open to alternative suggestions and happy to consider any advice you might have.

**Pull request merged**
