### PR TITLE
Remove making void explicit in functionMap.php

### PR DESCRIPTION
**Pull request by IanDelMar**
It's not necessary to add those extra `@phpstan-return void`.

### CODE REVIEW

**Comment by szepeviktor** [comment]
> It's not necessary

You are right.
But you talk to an Explicit Viktor :)
https://github.com/szepeviktor/very-clean-code#-write-positive-conditions

**Comment by IanDelMar** [comment]
https://github.com/szepeviktor/very-clean-docblocks :innocent:

**Comment by szepeviktor** [comment]
What is the before/after value of `\PHPStan\dumpType(add_meta_box(...som correct params...));`?

**Comment by IanDelMar** [comment]
1:0 explicity.
Before: `Dumped type: void`
After: `Dumped type: mixed`

Does this mean that we should add `@phpstan-return void` to all functions that return void, which we have been ignoring?

**Comment by johnbillion** [comment]
I don't think we can do that because some of those functions exit early (NEVER instead of void) and some are probably missing a `@return` tag in core but actually return a value.

**Comment by szepeviktor** [comment]
I let you take control of return type.
Just please do not take away void-s from users.

**Comment by IanDelMar** [comment]
> I don't think we can do that because some of those functions exit early (NEVER instead of void) and some are probably missing a `@return` tag in core but actually return a value.

The tricky part is separating void and never. I probably added most nevers in https://github.com/php-stubs/wordpress-stubs/pull/110 and documented which nevers are not caught by the `isNeverReturn()` method. The check for any return statement but `return;` should be feasible. Now thinking about it I have an idea. I'll check that and open an PR for discussion.

@szepeviktor In the meantime, feel free to close the pull request.

**Pull request closed without merging**
